name: build-devices

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    devices:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [macos-12]
                device: [ios, tvos, watchos]
        steps:
            -   uses: actions/checkout@v2
            -   name: build 
                run: |
                    swift --version
                    xcrun xcodebuild -list
                    xcrun xcodebuild build -scheme "DOM" -destination "generic/platform=${{ matrix.device }}"
                    xcrun xcodebuild build -scheme "HTML" -destination "generic/platform=${{ matrix.device }}"
                    xcrun xcodebuild build -scheme "RSS" -destination "generic/platform=${{ matrix.device }}"
                    xcrun xcodebuild build -scheme "SVG" -destination "generic/platform=${{ matrix.device }}"